name: Deploy Django App to EC2

on:
  push:
    branches:
      - main # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Install Docker if not present
            if ! command -v docker >/dev/null; then
              sudo yum install -y amazon-linux-extras
              sudo amazon-linux-extras enable docker
              sudo yum install docker -y
              sudo service docker start
              sudo usermod -aG docker ec2-user
            fi

            # Install Git if not present
            if ! command -v git >/dev/null; then
              sudo yum install git -y
            fi

            # Install Docker Compose if not present
            if ! command -v docker-compose >/dev/null; then
              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # Clone or pull the latest code
            if [ ! -d "~/dj-dockerservice/.git" ]; then
              echo "Cloning repository..."
              git clone https://github.com/ALASHI1/django-mircoservice.git ~/dj-dockerservice
            else
              echo "Pulling latest code..."
              cd ~/dj-dockerservice
              git pull origin main
            fi

            # Run the app
            cd ~/dj-dockerservice
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d
          timeout: 2m # Increase timeout to 2 minutes to handle delays during setup
