name: Deploy Django App to EC2

on:
  push:
    branches:
      - main # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Install Docker if not present
            if ! command -v docker >/dev/null; then
              curl -fsSL https://get.docker.com | sudo sh
              sudo usermod -aG docker $USER
            fi

            # Install Docker Compose if not present
            if ! command -v docker-compose >/dev/null; then
              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # Pull the latest code
            cd ~/dj-dockerservice || git clone https://github.com/ALASHI1/django-mircoservice.git ~/dj-dockerservice
            cd ~/dj-dockerservice
            git pull origin main

            # Run the app
            docker-compose down
            docker-compose up -d --build
